name: ZAP
on:
  push:
    branches:
      - githubcicd
      - githubcicd2
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Change script permission
        run: |
          chmod +x scripts/zap-script.sh
      - name: ZAP scan
        run: scripts/zap-script.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zap report
          path: |
            ./zap_baseline_report.html
